name: e2e

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
      - name: Setup Kustomize
        uses: fluxcd/pkg//actions/kustomize@main
      - name: Setup Kubebuilder
        uses: fluxcd/pkg//actions/kubebuilder@main
      - name: Setup Kubectl
        uses: fluxcd/pkg/actions/kubectl@main
        with:
          version: 1.21.2
      - name: Override Kubebuilder kubectl
        run: sudo cp /usr/local/bin/kubectl /home/runner/work/kustomize-controller/kustomize-controller/kubebuilder/bin/kubectl
      - name: Run tests
        run: make test
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Build container image
        run: make docker-build IMG=test/kustomize-controller:latest
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Load test image
        run: kind load docker-image test/kustomize-controller:latest
      - name: Deploy controllers
        run: |
          make dev-deploy IMG=test/kustomize-controller:latest
          kubectl -n kustomize-system rollout status deploy/source-controller --timeout=1m
          kubectl -n kustomize-system rollout status deploy/kustomize-controller --timeout=1m
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Run overlays tests
        run: |
          kubectl -n kustomize-system apply -k ./config/testdata/overlays
          kubectl -n kustomize-system wait kustomizations/webapp-staging --for=condition=ready --timeout=4m
          kubectl -n kustomize-system wait kustomizations/webapp-production --for=condition=ready --timeout=4m
      - name: Run dependencies tests
        run: |
          kubectl -n kustomize-system apply -k ./config/testdata/dependencies
          kubectl -n kustomize-system wait kustomizations/common --for=condition=ready --timeout=4m
          kubectl -n kustomize-system wait kustomizations/backend --for=condition=ready --timeout=4m
          kubectl -n kustomize-system wait kustomizations/frontend --for=condition=ready --timeout=4m
      - name: Run impersonation tests
        run: |
          kubectl -n impersonation apply -f ./config/testdata/impersonation
          kubectl -n impersonation wait kustomizations/podinfo --for=condition=ready --timeout=4m
          kubectl -n impersonation delete kustomizations/podinfo
          until kubectl -n impersonation get deploy/podinfo 2>&1 | grep NotFound ; do sleep 2; done
      - name: Logs
        run: |
          kubectl -n kustomize-system logs deploy/source-controller
          kubectl -n kustomize-system logs deploy/kustomize-controller
      - name: Debug failure
        if: failure()
        run: |
          which kubectl
          kubectl version
          kustomize version
          kubectl -n kustomize-system get gitrepositories -oyaml
          kubectl -n kustomize-system get kustomizations -oyaml
          kubectl -n kustomize-system get all
          kubectl -n kustomize-system logs deploy/source-controller
          kubectl -n kustomize-system logs deploy/kustomize-controller
